
name: "{{ cookiecutter.project_slug }}"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

query-comment: # Ask andrea
  comment: "{{ "{{" }} common.query_comment(node) {{ "}}" }}"
  job-label: True

quoting: # Ask andrea
  database: true
  schema: true
  identifier: true

vars:
  project_id: {{ cookiecutter.google_cloud_project_id }}
  database_id: {{ cookiecutter.database_id }}
  database_location: {{ cookiecutter.database_location }}

models:
  {{ cookiecutter.project_slug }}:
    raw:
      +materialized: table
    staging:
      +materialized: table
    datamart:
      +materialized: table

  dbt_project_evaluator: # ask andrea
    +enabled: '{{ "{{" }} '{{ "{{" }} env_var("DBT_ENV_NAME", "DEV") != "DEV" | as_bool {{ "}}" }}' {{ "}}" }}'
    +schema: dpe