
name: "{{ cookiecutter.project_slug }}"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.6.0", "<2.0.0"]

{% raw %}
query-comment:
  comment: "{{ common.query_comment(node) }}"
  job-label: True
{% endraw %}

quoting:
  database: true
  schema: true
  identifier: true

models:
  {{ cookiecutter.project_slug }}:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    datamarts:
      +materialized: table

{% raw %}
  dbt_project_evaluator:
    +enabled: '{{ '{{ env_var("DBT_ENV_NAME", "DEV") != "DEV" | as_bool }}' }}'
{% endraw %}