
name: "aaa"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.6.0", "<2.0.0"]


query-comment:
  comment: "{{ common.query_comment(node) }}"
  job-label: True


quoting:
  database: true
  schema: true
  identifier: true

models:
  aaa:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    datamarts:
      +materialized: table


  dbt_project_evaluator:
    +enabled: '{{ '{{ env_var("DBT_ENV_NAME", "DEV") != "DEV" | as_bool }}' }}'
